pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                git url: 'https://github.com/diyor0929/test_proj.git'
            }
        }

        stage('Build') {
            steps {
                sh 'echo "Building the app"'
            }
        }

        stage('Test') {
            steps {
                sh 'echo "Running tests"'
            }
        }

        stage('Deploy') {
            steps {
                sh 'echo "Deploying the app"'
            }
        }
    }
}

