pipeline{
    agent any
    stages{
        stage('checkout code'){
            steps{
                git https://github.com/diyor0929/test_proj
            }
        }
        stage('build'){
            steps{
                sh ' echo " Building the app" '
            }
        }
        stage('Test'){
            steps{
                sh ' echo "running test" '
            }
        }
        stages('Deploy'){
            steps{
                sh ' echo "Deploying" '
            }
        }
    }
}
