pipeline {
    agent any

    environment {
        REGISTRY = "registry.digitalocean.com/my-container-registry123"
        IMAGE_NAME   = "my-nodeapp"
        TAG      = "${BUILD_NUMBER}"
        CREDS    = "do-registry-creds"
        SERVER   = "root@104.248.86.154"
        APP_DIR  = "/opt/my-nodeapp"
    }

    stages {
        stage('Build Docker Image') {
            steps {
                sh '''   
                  docker build -t $REGISTRY/$IMAGE_NAME:$TAG my-nodeapp
                '''
            }
        }

        stage('Docker Login') {
    steps {
        withCredentials([string(credentialsId: 'do-registry-creds', variable: 'DO_TOKEN')]) {
            sh '''
              echo "$DO_TOKEN" | docker login $REGISTRY \
              -u oromovjavoxir@gmail.com --password-stdin
            '''
        }
    }
}


        stage('Push Docker Image') {
            steps {
                sh '''
                  docker push $REGISTRY/$IMAGE_NAME:$TAG
                  docker tag $REGISTRY/$IMAGE_NAME:$TAG $REGISTRY/$IMAGE_NAME:latest
                  docker push $REGISTRY/$IMAGE_NAME:latest

                '''
            }
        }
        stage('Deploy with docker compose'){
            steps{
                sshagent(['droplet-ssh-key']) {
                    sh """ 
                        ssh -o StrictHostKeyChecking=no $SERVER "
                            cd $APP_DIR && 
                            docker compose pull &&
                            docker compose up -d 
                        "
                    """
                }
            }
        }
    }

    post {
        always {
            sh 'docker logout $REGISTRY'
        }
    }
}

